=head1 Perl Mongers Contact Information

Please use the email addresses below to contact Perl Mongers

=head2 user_groups@pm.org

Any general queries about Perl Mongers. Anything that doesn't fit into
any of the other categories.

=head2 tech@pm.org

Any queries regarding the internet services (i.e. web space, mailing
lists and DNS) provided by Perl Mongers.

=head2 dns@pm.org

Any queries about the delegation of pm.org domains.

=head2 webmaster@pm.org

Any comments or suggestions about the web site.
