=head1 Perl Monger News

Latest news items from Perl Monger groups around the world.

If you have an story that you'd like us to feature here, then
please let us know.

=head2 Perl Monger T-Shirts at YAPC::Europe

19 Aug 2002

If you are going to YAPC::Europe and your local Perl Monger group
has its own t-shirt, please consider donating one to the auction
that will happen on the final day.

=head2 Damian Conway to speak in London

7 Aug 2002

Damian Conway will be speaking at two special london.pm meetings
in August. The meetings will be at the Conway Hall on Tueday 27th
(Life, the Universe and Everything) and Thursday 29th August (Perl
6 Perspective).

For more details see L<http://london.pm.org/meetings/>.

=head2 New Chief Perl Monger

6 Aug 2002

Dave Cross has been appointed the new Perl Mongers User Groups
Co-ordinator. Dave will be acting as liason between The Perl
Foundation and the 500 local Perl Monger groups.

=cut
