#!/bin/bash

cd
cd perlmongers
cvs commit perl_mongers.xml

for i in /web/gocho.pm.org/80/data/requests/verified/done/105*
do
	/home/pmadmin/bin/agtx $i
	/home/pmadmin/bin/addGroupToXML < spoonfeed
	mv perl_mongers.xml.new perl_mongers.xml
	ci -l perl_mongers.xml
done

